#:kivy 1.11.1


<gestionar_ventanas>:
    id: ventana_main_boxlayouts

    ScreenManager:
        id: scrn_mngr_main

        Screen:
            id: ventana1
            name:'ventana_login'
        Screen:
            id: ventana2
            name:'ventana_chooser'
        Screen:
            id: ventana3
            name:'ventana_controlador_ventas'
        Screen:
            id: ventana4
            name:'ventana_admin_modificar'      
